name: deeppurpose-md-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy<2.2.4
  - openmm
  - openmmforcefields
  - openff-toolkit
  - mdtraj=1.11.0
  - scikit-learn
  - pdbfixer
  - rdkit
  - pip
  - pip:
      - meeko
      - vina=1.2.6
      - scipy
      - gemmi
      - biopython
      - pubchempy
      - transformers
      - torch
      - tqdm
      - matplotlib
      - pandas
      - pandas-flavor
      - subword-nmt
      - sentencepiece
      # ✅ DeepPurpose deps
      - torch
      - tqdm
      - requests
      - wget
      - lifelines
      - prettytable
      - tensorboard
      - ax-platform
